version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    container_name: postgres_ecommerce
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
